#!/usr/bin/env bash
# installing Ngnix to the web server

sudo apt update && sudo apt upgrade;
sudo apt install nginx -y;
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
