#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/custom_404' <<EOF
server {
    listen 80 default_server;
    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
    
    # Additional Nginx configuration can be added here if needed.
}

EOF

# Create a symbolic link to enable the custom configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the changes
sudo service nginx restart

sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart

