#!/usr/bin/env bash
# installs and configures a nginx server with http header
sudo apt-get update;
sudo apt-get install nginx -y;
sudo service nginx start;
sudo mkdir -p /etc/nginx/html

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# Configure Nginx default site
sudo bash -c 'cat > /etc/nginx/sites-available/default' <<EOF
server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}
EOF

echo "Hello World!" | sudo tee /etc/nginx/html/index.html
header="add_header X-Served-By $(hostname);";
sudo sed -i '/server {/a \ \ \ \ '"$header"'' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx reload;
