#!/usr/bin/env bash
#checks whether nginx is listening on  port 80 if not change it to port 80
rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
