#!/usr/bin/env bash
# Using what we did for task #1, make your fix short and sweet.
sudo sed -i -e 's/user www-data/user nginx/' -e 's/80/8080/' /etc/nginx/nginx.conf /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
service apache2 stop
sudo -u nginx service nginx start